---
name: WireGuard Client
version: 0.2.2
slug: wireguard_client
description: Fast, modern, secure Wireguard tunnel (client)
url: https://github.com/bigmoby/addon-wireguard-client
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
apparmor: true
host_network: true
init: false
ports:
  80/tcp: 80
ports_description:
  80/tcp: WireGuard client status API
hassio_api: true
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
map:
  - ssl:rw
options:
  interface:
    private_key: ""
    address: 10.6.0.2
    dns: [ 8.8.8.8, 8.8.4.4]
    post_up: "iptables -t nat -A POSTROUTING -o wg0 -j MASQUERADE; iptables -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu"
    post_down: "iptables -t nat -D POSTROUTING -o wg0 -j MASQUERADE; iptables -D FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu"
    mtu: 1420
  peers:
    - public_key: ""
      pre_shared_key: ""
      endpoint: "xxxxxx.duckdns.com:51820"
      allowed_ips: [ "10.6.0.0/24" ]
      persistent_keep_alive: "25"
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  interface:
    private_key: password?
    address: str
    dns:
      - str?
    post_up: str?
    post_down: str?
    mtu: int
  peers:
    - public_key: str?
      pre_shared_key: str?
      endpoint: str
      allowed_ips:
        - str
      persistent_keep_alive: int
image: "bigmoby/{arch}-addon-wireguard-client"
